# Author: Glen Adams
version: '3.8'

services:
    db:
        container_name: "db"
        image: postgres
        build:
            context: ./db
            args:
                numcpu: 4
        ports:
          # 15432 used for external apps, docker containers still communicate over 5432
          - "15432:5432"
        volumes:
          - db:/var/lib/postgresql/data/
          - ./db/init:/docker-entrypoint-initdb.d/
        environment:
          - POSTGRES_USER=geog670
          - POSTGRES_PASSWORD=gadams
          - POSTGRES_DB=usgsdb
          - POSTGRES_MULTIPLE_DATABASES=usgsdb
          - PASSWORD=gadams
          - TZ=America/New_York
        restart: always
    python:
        container_name: python
        build: ./python
        volumes:
            - ./python:/python
        environment:
            - PYTHONUNBUFFERED=1
            - POSTGRES_SERVER=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=geog670
            - POSTGRES_PASSWORD=gadams
            - POSTGRES_DB=usgsdb
            - RUN_INTERVAL_MIN=1 # DEBUG SET TO 60 AT LEAST
            - PARALLEL_FACTOR=0.5
            - TZ=America/New_York
        restart: on-failure
    geoserver:
        container_name: geoserver
        image: kartoza/geoserver
        build: ./geoserver
        # volumes:
        #   - ./geoserver/geoserver-data:/opt/geoserver/data_dir Not needed, we are exclusively using the db container
        ports:
            - "8600:8080"
        restart: always
        environment:
            # - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
            # - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
            - GEOSERVER_ADMIN_USER=geog670
            - GEOSERVER_ADMIN_PASSWORD=gadams
            - INITIAL_MEMORY=2G
            - MAXIMUM_MEMORY=4G
volumes:
    db:
        driver: local